started:
  restart: always
  build: .
  expose:
    - "3000"
  ports:
    - "3000:3000"
  links:
    - mongo
  volumes:
    - ./:/opt/src
  environment:
    - PORT=3000
    - MONGO_URL=mongodb://mongo/started
mongo:
  image: mongo
  ports:
    - "27017:27017"
